const nxPreset = require('@nx/jest/preset').default;

/**
 * AUTO-GENERATED by scripts/sync-nx-packages.mjs
 * Do not edit manually.
 */
module.exports = {
  ...nxPreset,
  moduleNameMapper: {
    ...(nxPreset.moduleNameMapper || {}),

    '^@throwl\\/feature-auth$': '<rootDir>/libs/feature/auth/src/index.ts',
    '^@throwl\\/feature-friends$':
      '<rootDir>/libs/feature/friends/src/index.ts',
    '^@throwl\\/feature-game-doubles$':
      '<rootDir>/libs/feature/game-doubles/src/index.ts',
    '^@throwl\\/feature-game-x01$':
      '<rootDir>/libs/feature/game-x01/src/index.ts',
    '^@throwl\\/feature-home$': '<rootDir>/libs/feature/home/src/index.ts',
    '^@throwl\\/feature-new-game$':
      '<rootDir>/libs/feature/new-game/src/index.ts',
    '^@throwl\\/feature-played-games$':
      '<rootDir>/libs/feature/played-games/src/index.ts',
    '^@throwl\\/feature-settings$':
      '<rootDir>/libs/feature/settings/src/index.ts',
    '^@throwl\\/shared-constants$':
      '<rootDir>/libs/shared/constants/src/index.ts',
    '^@throwl\\/shared-data-access-firebase$':
      '<rootDir>/libs/shared/data-access/firebase/src/index.ts',
    '^@throwl\\/shared-data-access-game$':
      '<rootDir>/libs/shared/data-access/game/src/index.ts',
    '^@throwl\\/shared-data-access-user$':
      '<rootDir>/libs/shared/data-access/user/src/index.ts',
    '^@throwl\\/shared-domain-game-rules$':
      '<rootDir>/libs/shared/domain/game-rules/src/index.ts',
    '^@throwl\\/shared-domain-models$':
      '<rootDir>/libs/shared/domain/models/src/index.ts',
    '^@throwl\\/shared-hooks$': '<rootDir>/libs/shared/hooks/src/index.ts',
    '^@throwl\\/shared-layouts$': '<rootDir>/libs/shared/layouts/src/index.ts',
    '^@throwl\\/shared-theme$': '<rootDir>/libs/shared/theme/src/index.ts',
    '^@throwl\\/shared-ui$': '<rootDir>/libs/shared/ui/src/index.ts',
  },
};
