const path = require('path');
const nxPreset = require('@nx/jest/preset').default;

/**
 * AUTO-GENERATED by scripts/sync-nx-packages.mjs
 * Do not edit manually.
 */
const fromRoot = (projectPath) => path.join(__dirname, projectPath);

module.exports = {
  ...nxPreset,

  moduleNameMapper: {
    ...(nxPreset.moduleNameMapper || {}),

    '^@throwl\/feature-auth$': fromRoot('libs/feature/auth/src/index.ts'),
    '^@throwl\/feature-friends$': fromRoot('libs/feature/friends/src/index.ts'),
    '^@throwl\/feature-game-doubles$': fromRoot(
      'libs/feature/game-doubles/src/index.ts',
    ),
    '^@throwl\/feature-game-x01$': fromRoot(
      'libs/feature/game-x01/src/index.ts',
    ),
    '^@throwl\/feature-home$': fromRoot('libs/feature/home/src/index.ts'),
    '^@throwl\/feature-new-game$': fromRoot(
      'libs/feature/new-game/src/index.ts',
    ),
    '^@throwl\/feature-played-games$': fromRoot(
      'libs/feature/played-games/src/index.ts',
    ),
    '^@throwl\/feature-profile$': fromRoot('libs/feature/profile/src/index.ts'),
    '^@throwl\/shared-constants$': fromRoot(
      'libs/shared/constants/src/index.ts',
    ),
    '^@throwl\/shared-data-access-firebase$': fromRoot(
      'libs/shared/data-access-firebase/src/index.ts',
    ),
    '^@throwl\/shared-data-access-game$': fromRoot(
      'libs/shared/data-access-game/src/index.ts',
    ),
    '^@throwl\/shared-data-access-user$': fromRoot(
      'libs/shared/data-access-user/src/index.ts',
    ),
    '^@throwl\/shared-domain-game-rules$': fromRoot(
      'libs/shared/domain/game-rules/src/index.ts',
    ),
    '^@throwl\/shared-domain-models$': fromRoot(
      'libs/shared/domain/models/src/index.ts',
    ),
    '^@throwl\/shared-hooks$': fromRoot('libs/shared/hooks/src/index.ts'),
    '^@throwl\/shared-layouts$': fromRoot('libs/shared/layouts/src/index.ts'),
    '^@throwl\/shared-theme$': fromRoot('libs/shared/theme/src/index.ts'),
    '^@throwl\/shared-ui$': fromRoot('libs/shared/ui/src/index.ts'),
  },
};
