default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

platform :ios do
  lane :update_version do |options|
    increment_version_number(
      version_number: options[:version],
      xcodeproj: "throwl.xcodeproj"
    )
    increment_build_number(xcodeproj: "throwl.xcodeproj")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    setup_ci

    cocoapods(
      clean_install: true
    )

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      api_key: api_key
    )

    build_app(
      scheme: "throwl",
      workspace: "throwl.xcworkspace",
      clean: true,
      export_method: "app-store"
    )

    upload_to_testflight(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./throwl.ipa"
    )
  end
end
