source "https://rubygems.org"

ruby "3.3.6"

gem "fastlane"

group :ios do
  gem "cocoapods", ">= 1.13", "!= 1.15.0", "!= 1.15.1"
  gem "activesupport", ">= 6.1.7.5", "!= 7.1.0"
  gem "xcodeproj", "< 1.26.0"
end

plugins_path = File.join(__dir__, "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
