name: Setup action jobs
inputs:
  os:
    type: string
    required: true
  bundle:
    type: boolean
    required: true
  working_directory:
    type: string
    required: false
    description: One of `ios` or `android`
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v4
      id: node_modules-cache
      with:
        path: |
          **/node_modules
        key: NM-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          NM-

    - name: Install npm dependencies
      shell: bash
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Use Ruby v3.3.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
        bundler-cache: true

    - name: Install bundle
      shell: bash
      if: ${{ inputs.bundle }}
      working-directory: ${{ inputs.working_directory }}
      run: bundle install --jobs 4 --retry 3
