# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end


lane :beta do
  desc "Push a new beta build to TestFlight"

  if is_ci
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end

  match(
    type: "appstore",
    readonly: is_ci,
    keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
    keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
  )

  build_app(
    scheme: "Runner",
    workspace: "Runner.xcworkspace",
    export_method: "app-store"
  )

  upload_to_testflight
end
