default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end


lane :beta do
  desc "Push a new beta build to TestFlight"

  app_store_connect_api_key(
    key_id: ENV["FASTLANE_KEY_ID"],
    issuer_id: ENV["FASTLANE_ISSUER_ID"],
    key_filepath: "./authkey.p8",
  )

  if is_ci
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
  end

  match(
    type: "appstore",
    readonly: is_ci,
    keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
    keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
  )

  build_app(
    scheme: "Runner",
    workspace: "Runner.xcworkspace",
    export_method: "app-store"
  )

  upload_to_testflight
end
