default_platform(:android)

platform :android do
  desc "Increment versionCode and set versionName"
  lane :update_version do |options|
    android_set_version_name(version_name: options[:version])
    android_set_version_code
  end

  desc "Submit a new Beta Build"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'beta')
  end
end
