name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: 10.24.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: |
            package.json
            pnpm-lock.yaml

      - name: Use Java 21 for Firebase Emulator
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'zulu'
          java-version: '21'

      - run: pnpm install --frozen-lockfile

      - name: Derive SHAs for Nx affected
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
        with:
          main-branch-name: master

      - name: Validate affected projects
        run: pnpm nx affected -t lint,typecheck,test --parallel --maxParallel=5

      - name: Prettier (affected)
        run: pnpm nx format:check --affected

      - name: Firestore Rules
        run: pnpm test:firestore-rules
